kernelsu-objs := ksu.o
kernelsu-objs += allowlist.o
kernelsu-objs += dynamic_manager.o
kernelsu-objs += app_profile.o
kernelsu-objs += apk_sign.o
kernelsu-objs += sucompat.o

kernelsu-objs += throne_tracker.o
kernelsu-objs += pkg_observer.o
kernelsu-objs += setuid_hook.o

ifeq ($(CONFIG_KSU_MANUAL_HOOK), y)
ifeq ($(shell test $(VERSION) -lt 6 || { test $(VERSION) -eq 6 && test $(PATCHLEVEL) -lt 8; } && echo y),y)
kernelsu-objs += lsm_hooks.o
endif
endif

kernelsu-objs += kernel_compat.o
kernelsu-objs += kernel_umount.o
kernelsu-objs += supercalls.o
kernelsu-objs += su_mount_ns.o
kernelsu-objs += feature.o
kernelsu-objs += throne_tracker.o
kernelsu-objs += ksud.o
kernelsu-objs += seccomp_cache.o
kernelsu-objs += file_wrapper.o
kernelsu-objs += sulog.o
kernelsu-objs += manager.o

kernelsu-objs += selinux/selinux.o
kernelsu-objs += selinux/sepolicy.o
kernelsu-objs += selinux/rules.o

ccflags-y += -Wno-implicit-function-declaration -Wno-strict-prototypes 
ccflags-y += $(call cc-disable-warning, int-conversion)
ccflags-y += -Wno-declaration-after-statement -Wno-unused-function -Wno-unused-variable -Wno-missing-braces
ccflags-y += -Wno-int-to-pointer-cast -Wno-declaration-after-statement

ccflags-y += -I$(srctree)/security/selinux -I$(srctree)/security/selinux/include
ccflags-y += -I$(objtree)/security/selinux -include $(srctree)/include/uapi/asm-generic/errno.h

obj-$(CONFIG_KSU) += kernelsu.o

obj-$(CONFIG_KPM) += kpm/

REPO_NAME := ReSukiSU

KDIR := $(KDIR)

GIT_BIN := /usr/bin/env PATH="$$PATH":/usr/bin:/usr/local/bin git
CURL_BIN := /usr/bin/env PATH="$$PATH":/usr/bin:/usr/local/bin curl

KSU_SRC := $(realpath $(dir $(abspath $(lastword $(MAKEFILE_LIST)))))

LOCAL_GIT_EXISTS := $(shell test -e $(KSU_SRC)/../.git && echo 1 || echo 0)

ifeq ($(LOCAL_GIT_EXISTS),0)
$(info -- Can't find $(REPO_NAME) git submodule!)
$(info -- If you are using bazel to build this kernel,)
$(info -- Please go to Kbuild and change KSU_SRC to the absolute path of the KSU kernel folder.)
$(error You should use $(REPO_NAME) as a git submodule instead of copying code directly)
endif

$(shell cd $(KSU_SRC); [ -f ../.git/shallow ] && $(GIT_BIN) fetch --unshallow)
KSU_LOCAL_VERSION := $(shell cd $(KSU_SRC); $(GIT_BIN) rev-list --count HEAD)
KSU_VERSION := $(shell expr 30000 + $(KSU_LOCAL_VERSION) + 700)

KSU_TAG_NAME    := $(shell cd $(KSU_SRC); $(GIT_BIN) describe --abbrev=0 --tags 2>/dev/null || echo "unknown")
KSU_COMMIT_SHA  := $(shell cd $(KSU_SRC); $(GIT_BIN) rev-parse --short=8 HEAD 2>/dev/null || echo "unknown")
KSU_BRANCH_NAME := $(shell cd $(KSU_SRC); $(GIT_BIN) branch --show-current 2>/dev/null || echo "unknown")

# make ddk happy
ifneq ($(KDIR),)
CONFIG_KSU_FULL_NAME_FORMAT := "%TAG_NAME%-%COMMIT_SHA%@%REPO_NAME%"
endif

# call subst to process placeholders
KSU_VERSION_FULL := $(subst ",,$(CONFIG_KSU_FULL_NAME_FORMAT))
KSU_VERSION_FULL := $(subst %TAG_NAME%,$(KSU_TAG_NAME),$(KSU_VERSION_FULL))
KSU_VERSION_FULL := $(subst %COMMIT_SHA%,$(KSU_COMMIT_SHA),$(KSU_VERSION_FULL))
KSU_VERSION_FULL := $(subst %REPO_NAME%,$(REPO_NAME),$(KSU_VERSION_FULL))
KSU_VERSION_FULL := $(subst %BRANCH_NAME%,$(KSU_BRANCH_NAME),$(KSU_VERSION_FULL))
KSU_VERSION_FULL := $(subst %KSU_VERSION%,$(KSU_VERSION),$(KSU_VERSION_FULL))

$(info -- $(REPO_NAME) version code: $(KSU_VERSION))
$(info -- $(REPO_NAME) version name: $(KSU_VERSION_FULL))

ccflags-y += -DKSU_VERSION=$(KSU_VERSION)
ccflags-y += -DKSU_VERSION_FULL=\"$(KSU_VERSION_FULL)\"

ifeq ($(CONFIG_KSU_MULTI_MANAGER_SUPPORT), y)
$(info -- Supported Unofficial Manager: MKSU, RKSU, KOWSU, SukiSU-Ultra, ReSukiSU )
endif

ifeq ($(CONFIG_KSU_MANUAL_HOOK), y)
$(info -- $(REPO_NAME): using KSU_MANUAL_HOOK)
else ifeq ($(CONFIG_KSU_SUSFS), y)
$(info -- $(REPO_NAME): using SUSFS_INLINE_HOOK)
else
ccflags-y += -DKSU_TP_HOOK
KSU_TP_HOOK := y
$(info -- $(REPO_NAME): using KSU_TRACEPOINT_HOOK)
endif

KERNEL_VERSION := $(VERSION).$(PATCHLEVEL)
KERNEL_TYPE := Non-GKI
# Check for GKI 2.0 (5.10+ or 6.x+)
ifneq ($(shell test \( $(VERSION) -ge 5 -a $(PATCHLEVEL) -ge 10 \) -o $(VERSION) -ge 6; echo $$?),0)
# Check for GKI 1.0 (5.4)
ifeq ($(shell test $(VERSION)-$(PATCHLEVEL) = 5-4; echo $$?),0)
KERNEL_TYPE := GKI 1.0
endif
else
KERNEL_TYPE := GKI 2.0
endif
$(info -- KERNEL_VERSION: $(KERNEL_VERSION))
$(info -- KERNEL_TYPE: $(KERNEL_TYPE))

# Check if KPM is enabled
ifeq ($(CONFIG_KPM), y)
$(info -- KPM is enabled)
$(info -- WARNING, This feature is unstable!!! You are WARNED!!!)
else
$(info -- KPM is disabled)
endif

ifeq ($(KSU_TP_HOOK), y)
kernelsu-objs += syscall_hook_manager.o
kernelsu-objs += util.o
endif

# SELinux drivers check
ifeq ($(shell grep -q "current_sid(void)" $(srctree)/security/selinux/include/objsec.h; echo $$?),0)
$(info -- $(REPO_NAME)/compat: current_sid found)
ccflags-y += -DKSU_COMPAT_HAS_CURRENT_SID
endif
ifeq ($(shell grep -q "struct selinux_state " $(srctree)/security/selinux/include/security.h; echo $$?),0)
$(info -- $(REPO_NAME)/compat: selinux_state found)
ccflags-y += -DKSU_COMPAT_HAS_SELINUX_STATE
endif

# Handle optional backports
ifeq ($(shell grep -q "strncpy_from_user_nofault" $(srctree)/include/linux/uaccess.h; echo $$?),0)
$(info -- $(REPO_NAME)/compat: strncpy found)
ccflags-y += -DKSU_OPTIONAL_STRNCPY
endif

ifeq ($(shell grep -q "ssize_t kernel_read" $(srctree)/fs/read_write.c; echo $$?),0)
$(info -- $(REPO_NAME)/compat: kernel_read found)
ccflags-y += -DKSU_OPTIONAL_KERNEL_READ
endif

ifeq ($(shell grep "ssize_t kernel_write" $(srctree)/fs/read_write.c | grep -q "const void" ; echo $$?),0)
$(info -- $(REPO_NAME)/compat: kernel_write found)
ccflags-y += -DKSU_OPTIONAL_KERNEL_WRITE
endif

ifeq ($(shell grep -q "int\s\+path_mount" $(srctree)/fs/namespace.c; echo $$?),0)
$(info -- $(REPO_NAME)/compat: path_mount found)
ccflags-y += -DKSU_HAS_PATH_MOUNT
endif

ifeq ($(shell grep -q "int\s\+path_umount" $(srctree)/fs/namespace.c; echo $$?),0)
$(info -- $(REPO_NAME)/compat: path_umount found)
ccflags-y += -DKSU_HAS_PATH_UMOUNT
endif

ifeq ($(shell grep -q "inode_security_struct\s\+\*selinux_inode" $(srctree)/security/selinux/include/objsec.h; echo $$?),0)
$(info -- $(REPO_NAME)/compat: selinux_inode found)
ccflags-y += -DKSU_OPTIONAL_SELINUX_INODE
endif

ifeq ($(shell grep -q "task_security_struct\s\+\*selinux_cred" $(srctree)/security/selinux/include/objsec.h; echo $$?),0)
$(info -- $(REPO_NAME)/compat: selinux_cred found)
ccflags-y += -DKSU_OPTIONAL_SELINUX_CRED
endif

# seccomp_types.h was added in 6.7
ifeq ($(shell grep -q "atomic_t\s\+filter_count" $(srctree)/include/linux/seccomp.h $(srctree)/include/linux/seccomp_types.h; echo $$?),0)
$(info -- $(REPO_NAME)/compat: seccomp_filter_count found)
ccflags-y += -DKSU_OPTIONAL_SECCOMP_FILTER_CNT
endif

# some old kernels backport this, so check whether put_seccomp_filter still exists
ifneq ($(shell grep -wq "put_seccomp_filter" $(srctree)/kernel/seccomp.c $(srctree)/include/linux/seccomp.h; echo $$?),0)
$(info -- $(REPO_NAME)/compat: put_seccomp_filter found)
ccflags-y += -DKSU_OPTIONAL_SECCOMP_FILTER_RELEASE
endif

ifeq ($(shell grep -q "security_inode_init_security_anon" $(srctree)/include/linux/security.h; echo $$?),0)
$(info -- $(REPO_NAME)/compat: security_inode_init_security_anon found)
ccflags-y += -DKSU_OPTIONAL_HAS_INIT_SEC_ANON
endif

ifeq ($(shell grep -q "anon_inode_getfd_secure" $(srctree)/fs/anon_inodes.c; echo $$?),0)
$(info -- $(REPO_NAME)/compat: anon_inode_getfd_secure found)
ccflags-y += -DKSU_HAS_GETFD_SECURE
endif

ifeq ($(shell grep -A1 "^int vfs_getattr" $(srctree)/fs/stat.c | grep -q "query_flags"; echo $$?),0)
$(info -- $(REPO_NAME)/compat: vfs_getattr() found)
ccflags-y += -DKSU_HAS_NEW_VFS_GETATTR
endif

ifeq ($(shell grep -q "static inline struct inode \*file_inode" $(srctree)/include/linux/fs.h; echo $$?),0)
$(info -- $(REPO_NAME)/compat: file_inode() found)
ccflags-y += -DKSU_UL_HAS_FILE_INODE
endif

# Checks Samsung
ifeq ($(shell grep -q "CONFIG_KDP_CRED" $(srctree)/kernel/cred.c; echo $$?),0)
$(info -- $(REPO_NAME)/compat/samsung: CONFIG_KDP_CRED found)
ccflags-y += -DSAMSUNG_UH_DRIVER_EXIST
endif

ifeq ($(shell grep -q "SEC_SELINUX_PORTING_COMMON" $(srctree)/security/selinux/avc.c; echo $$?),0)
$(info -- $(REPO_NAME)/compat/samsung: SEC_SELINUX_PORTING_COMMON found)
ccflags-y += -DSAMSUNG_SELINUX_PORTING
endif

# For Huawei EMUI10+ Cheak  
# Scan Kernel Tree to find CONFIG_HKIP_SELINUX_PROT in ebitmap.h
ifeq ($(shell grep -q "CONFIG_HKIP_SELINUX_PROT" $(srctree)/security/selinux/ss/ebitmap.h 2>/dev/null; echo $$?),0)
  $(info -- $(REPO_NAME): CONFIG_HKIP_SELINUX_PROT found! Exporting CONFIG_IS_HISI_HM2)
  export CONFIG_IS_HISI_HM2 := 1
  ccflags-y += -DCONFIG_IS_HISI_HM2=1
else
  $(info -- $(REPO_NAME): Standard kernel detected (no CONFIG_HKIP_SELINUX_PROT).)
endif

# Function proc_ops check
ifeq ($(shell grep -q "struct proc_ops " $(srctree)/include/linux/proc_fs.h; echo $$?),0)
$(info -- $(REPO_NAME)/compat: proc_ops found)
ccflags-y += -DKSU_COMPAT_HAS_PROC_OPS
endif

# Bitmap zalloc
# https://github.com/torvalds/linux/commit/c42b65e363ce97a828f81b59033c3558f8fa7f70
ifeq ($(shell grep -q "bitmap_zalloc" $(srctree)/include/linux/bitmap.h; echo $$?),0)
$(info -- $(REPO_NAME)/compat: bitmap_zalloc found)
ccflags-y += -DKSU_COMPAT_HAS_BITMAP_ALLOC_HELPER
endif

# policy mutex
# kernel 5.10+
ifeq ($(shell grep -q "policy_mutex" $(srctree)/security/selinux/include/security.h; echo $$?),0)
$(info -- $(REPO_NAME)/compat: policy_mutex found)
ccflags-y += -DKSU_COMPAT_HAS_POLICY_MUTEX
endif

# policy rwlock
# kernel 4.14-
ifeq ($(shell grep -q "^DEFINE_RWLOCK(policy_rwlock);" $(srctree)/security/selinux/ss/services.c; echo $$?),0)
$(info -- $(REPO_NAME)/compat: exported policy_rwlock found!)
ccflags-y += -DKSU_COMPAT_HAS_EXPORTED_POLICY_RWLOCK
endif

# Custom Signs
ifdef KSU_EXPECTED_SIZE
ccflags-y += -DEXPECTED_SIZE=$(KSU_EXPECTED_SIZE)
$(info -- Custom KernelSU Manager signature size: $(KSU_EXPECTED_SIZE))
endif

ifdef KSU_EXPECTED_HASH
ccflags-y += -DEXPECTED_HASH=\"$(KSU_EXPECTED_HASH)\"
$(info -- Custom KernelSU Manager signature hash: $(KSU_EXPECTED_HASH))
endif

ifdef KSU_MANAGER_PACKAGE
ccflags-y += -DKSU_MANAGER_PACKAGE=\"$(KSU_MANAGER_PACKAGE)\"
$(info -- KernelSU Manager package name: $(KSU_MANAGER_PACKAGE))
endif

## For susfs stuff ##
ifeq ($(CONFIG_KSU_SUSFS), y)
ifeq ($(shell test -e $(srctree)/fs/susfs.c; echo $$?),0)
$(eval SUSFS_VERSION=$(shell cat $(srctree)/include/linux/susfs.h | grep -E '^#define SUSFS_VERSION' | cut -d' ' -f3 | sed 's/"//g'))
$(info )
$(info -- SUSFS_VERSION: $(SUSFS_VERSION))
else
$(info -- You have not integrated susfs in your kernel yet.)
$(info -- Read: https://gitlab.com/simonpunk/susfs4ksu)
$(error You should integrate susfs in your kernel.)
endif
endif

# manual hook check
ifeq ($(CONFIG_KSU_MANUAL_HOOK), y)

  ifeq ($(CONFIG_KSU_MANUAL_HOOK_AUTO_SETUID_HOOK), y)
    $(info -- $(REPO_NAME)/manual_hook: You are using LSM hooks for setuid hooks.)
    ifeq ($(VERSION),6)
      ifeq ($(shell test $(PATCHLEVEL) -ge 8 && echo y),y)
        $(info -- You can't use LSM hooks for kernel version higher than 6.8)
        $(info -- You should turn off CONFIG_KSU_MANUAL_HOOK_AUTO_SETUID_HOOK and hook setresuid manually)
        $(info -- Read: https://resukisu.github.io/guide/manual-integrate.html)
        $(error You can't use LSM hooks when kernel version >= 6.8)
      endif
    endif
  else
    $(info -- $(REPO_NAME)/manual_hook: You are using a manual setresuid hook for setuid hooks.)

    ifeq ($(shell grep -q "ksu_handle_setresuid" $(srctree)/kernel/sys.c; echo $$?),0)
      $(info -- $(REPO_NAME)/manual_hook: ksu_handle_setresuid found)
    else
      $(info -- You lost ksu_handle_setresuid hook in your kernel)
      $(info -- Read: https://resukisu.github.io/guide/manual-integrate.html)
      $(error You should integrate $(REPO_NAME) in your kernel.)
    endif
  endif

  ifeq ($(CONFIG_KSU_MANUAL_HOOK_AUTO_INITRC_HOOK), y)
    $(info -- $(REPO_NAME)/manual_hook: You are using LSM hooks for init rc hooks.)
    ifeq ($(VERSION),6)
      ifeq ($(shell test $(PATCHLEVEL) -ge 8 && echo y),y)
        $(info -- You can't use LSM hooks for kernel version higher than 6.8)
        $(info -- You should turn off CONFIG_KSU_MANUAL_HOOK_AUTO_INITRC_HOOK and hook sys_read manually.)
        $(info -- Read: https://resukisu.github.io/guide/manual-integrate.html)
        $(error You can't use LSM hooks when kernel version >= 6.8)
      endif
    endif
  else
    $(info -- $(REPO_NAME)/manual_hook: You are using a manual sys_read hook for init rc hooks.)

    ifeq ($(shell grep -q "ksu_handle_sys_read" $(srctree)/fs/read_write.c; echo $$?),0)
      $(info -- $(REPO_NAME)/manual_hook: ksu_handle_sys_read found)
    else
      $(info -- You lost ksu_handle_sys_read hook in your kernel)
      $(info -- Read: https://resukisu.github.io/guide/manual-integrate.html)
      $(error You should integrate $(REPO_NAME) in your kernel.)
    endif
  endif

  ifeq ($(shell grep -q "ksu_vfs_read_hook" $(srctree)/fs/read_write.c; echo $$?),0)
    $(info -- ksu_vfs_read_hook is incompatible hook)
    $(info -- Read: https://resukisu.github.io/guide/manual-integrate.html)
    $(error You should integrate $(REPO_NAME) in your kernel correctly.)
  endif

  ifeq ($(shell grep -q "is_ksu_transition" $(srctree)/security/selinux/hooks.c; echo $$?),0)
    $(info -- is_ksu_transition is incompatible hook)
    $(info -- Read: https://resukisu.github.io/guide/manual-integrate.html)
    $(error You should integrate $(REPO_NAME) in your kernel correctly.)
  endif

  ifeq ($(CONFIG_KSU_MANUAL_HOOK_AUTO_INPUT_HOOK), y)
    $(info -- $(REPO_NAME)/manual_hook: You are using input_handler for input hooks.)
  else
    ifeq ($(shell grep -q "ksu_handle_input_handle_event" $(srctree)/drivers/input/input.c; echo $$?),0)
      $(info -- $(REPO_NAME)/manual_hook: ksu_handle_input_handle_event found)
    else
      $(info -- You lost ksu_handle_input_handle_event hook in your kernel)
      $(info -- Read: https://resukisu.github.io/guide/manual-integrate.html)
      $(error You should integrate $(REPO_NAME) in your kernel.)
    endif
  endif

  ifeq ($(shell grep -q "ksu_handle_execveat" $(srctree)/fs/exec.c; echo $$?),0)
    $(info -- $(REPO_NAME)/manual_hook: ksu_handle_execveat found)
  else
    $(info -- You lost ksu_handle_execveat hook in your kernel)
    $(info -- Read: https://resukisu.github.io/guide/manual-integrate.html)
    $(error You should integrate $(REPO_NAME) in your kernel.)
  endif

  ifeq ($(shell grep -q "ksu_handle_faccessat" $(srctree)/fs/open.c; echo $$?),0)
    $(info -- $(REPO_NAME)/manual_hook: ksu_handle_faccessat found)
  else
    $(info -- You lost ksu_handle_faccessat hook in your kernel)
    $(info -- Read: https://resukisu.github.io/guide/manual-integrate.html)
    $(error You should integrate $(REPO_NAME) in your kernel.)
  endif

  ifeq ($(shell grep -q "ksu_handle_stat" $(srctree)/fs/stat.c; echo $$?),0)
    $(info -- $(REPO_NAME)/manual_hook: ksu_handle_stat found)
  else
    $(info -- You lost ksu_handle_stat hook in your kernel)
    $(info -- Read: https://resukisu.github.io/guide/manual-integrate.html)
    $(error You should integrate $(REPO_NAME) in your kernel.)
  endif

  ifeq ($(shell grep -q "ksu_handle_newfstat_ret" $(srctree)/fs/stat.c; echo $$?),0)
    $(info -- $(REPO_NAME)/manual_hook: ksu_handle_newfstat_ret found)
  else
    $(info -- You lost ksu_handle_newfstat_ret hook in your kernel)
    $(info -- Read: https://resukisu.github.io/guide/manual-integrate.html)
    $(error You should integrate $(REPO_NAME) in your kernel.)
  endif 

  ifeq ($(shell grep -q "ksu_handle_fstat64_ret" $(srctree)/fs/stat.c; echo $$?),0)
    $(info -- $(REPO_NAME)/manual_hook: ksu_handle_fstat64_ret found)
  else
    $(info -- You lost ksu_handle_fstat64_ret hook in your kernel)
    $(info -- Read: https://resukisu.github.io/guide/manual-integrate.html)
    $(error You should integrate $(REPO_NAME) in your kernel.)
  endif

  ifeq ($(shell grep -q "ksu_handle_sys_reboot" $(srctree)/kernel/reboot.c; echo $$?),0)
    $(info -- $(REPO_NAME)/manual_hook: ksu_handle_sys_reboot found)
  else
    $(info -- You lost ksu_handle_sys_reboot hook in your kernel)
    $(info -- Read: https://resukisu.github.io/guide/manual-integrate.html)
    $(error You should integrate $(REPO_NAME) in your kernel.)
  endif
endif

ifeq ($(CONFIG_KSU),y)
  ifneq ($(KERNEL_TYPE), GKI 2.0)
      ifeq ($(KSU_TP_HOOK), y)
          $(info -- $(REPO_NAME) TP Hooks are only supported on GKI 2.0 kernels.)
          $(info -- Current Kernel Type: $(KERNEL_TYPE))
          $(info -- If you really want to continue, go to Kbuild and comment out this warning.)
          $(info -- Usually, this error occurs because you forgot to enable some kernel configurations.)
          $(info -- Read: https://resukisu.github.io/guide/manual-integrate.html)
          $(error TP hooks are incompatible with Non-GKI/GKI 1.0 kernels in this configuration.)
      endif
  endif
endif

# Keep a new line here!! Because someone may append config
